#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
server:
  port: 9003
spring:
  application:
    name: ihrm-employee #指定服务名
  datasource:
    url: jdbc:mysql://localhost:3306/ihrm?serverTimezone=Asia/Shanghai
    username: root
    password: 991228
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379

