#eureka服务的配置文件
server:
  port: 6868 #服务端口
eureka:
  client:
    register-with-eureka: false #不注册自己到eureka服务中
    fetch-registry: false #不从eureka中获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ihrm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 991228
    driver-class-name: com.mysql.cj.jdbc.Driver
