#服务配置
server:
  port: 9002
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-system #指定服务名
    #2.数据库连接池
  datasource:
    url: jdbc:mysql://localhost:3306/ihrm?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 991228
    #3.JPA
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
jwt:
  config:
    key: "saas-ihrm"
    ttl: 3600000
#微服务注册到eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/